const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const readSource = (workspacePath) =>
  fs.readFileSync(path.join(process.cwd(), workspacePath), "utf8");

test("faithful output panel uses valuation-shell-first p-adic columns with derived w_norm", () => {
  const source = readSource("src/components/padic-faithful/PAdicOutputsPanel.vue");

  assert.match(source, /Statistical Outputs omega_i/);
  assert.match(source, /valuation shell/);
  assert.match(source, /digit prefix/);
  assert.match(source, /w_norm \(Derived\)/);
  assert.match(source, /digits \(base p\)/);
  assert.equal(source.toLowerCase().includes("probability"), false);
  assert.equal(source.includes("formatPercent("), false);
  assert.equal(source.includes("prob-bar"), false);
});

test("faithful workbench keeps operator and sovm primary labels", () => {
  const app = readSource("src/App.vue");
  const workbench = readSource("src/components/padic-faithful/PAdicFaithfulWorkbench.vue");
  const rho = readSource("src/components/padic-faithful/PAdicRhoPanel.vue");
  const sovm = readSource("src/components/padic-faithful/PAdicSovmPanel.vue");
  const sources = readSource("src/components/padic-faithful/PAdicSourcesPanel.vue");
  const input = readSource("src/components/padic-faithful/PAdicGeneralInputPanel.vue");
  const circuit = readSource("src/components/padic-faithful/PAdicCircuitPanel.vue");
  const stages = readSource("src/components/padic-faithful/PAdicStageCards.vue");
  const glyph = readSource("src/components/padic-faithful/PAdicNumericGlyph.vue");
  const derivedMap = readSource("src/components/padic-faithful/PAdicDerivedMap.vue");

  assert.match(app, /p-adic \(experimental\)/);
  assert.match(rho, /State Operator rho/);
  assert.match(rho, /support omega_i/);
  assert.match(rho, /non-zero entries/);
  assert.match(rho, /non-zero off-diagonal/);
  assert.match(rho, /off-diagonal preview/);
  assert.match(sovm, /SOVM Effects F_i/);
  assert.match(input, /General Qubit Input/);
  assert.match(input, /Prime p/);
  assert.match(input, /Prime Basis/);
  assert.match(input, /p = \{\{ pAdicFaithfulState\.prime \}\}/);
  assert.match(input, /Configure each qubit separately/);
  assert.match(input, /preparedInputs/);
  assert.match(input, /Q\{\{ index \}\}/);
  assert.match(input, /2\^n x 2\^n/);
  assert.match(input, /presetCards/);
  assert.match(input, /presetSummaryForInput/);
  assert.equal(input.includes("Use for outputs"), false);
  assert.equal(input.includes("Active output qubit"), false);
  assert.match(circuit, /p-adic Circuit/);
  assert.match(circuit, /active tool:/);
  assert.match(circuit, /const gates = \[\"I\", \"X\", \"Z\", \"H\", \"CNOT\", \"M\"\]/);
  assert.match(circuit, /selectGate\(gate\)/);
  assert.match(circuit, /CNOT uses control-then-target click placement/);
  assert.match(circuit, /Alt\+Click a slot clears that slot/);
  assert.match(circuit, /CNOT_CONTROL/);
  assert.match(circuit, /CNOT_TARGET/);
  assert.match(circuit, /column-connectors/);
  assert.match(circuit, /column-connector cnot/);
  assert.match(circuit, /column-quantum-register/);
  assert.match(circuit, /quantumRowCenterY/);
  assert.match(circuit, /connectorSegments\(columnIndex\)/);
  assert.match(circuit, /connectorStyle\(connector\)/);
  assert.doesNotMatch(circuit, /minmax\(56px, 1fr\)/);
  assert.match(circuit, /isPendingCnotTarget/);
  assert.match(circuit, /@mouseleave="handleSlotLeave\(columnIndex, row\)"/);
  assert.match(circuit, /setFaithfulColumnGate\(columnIndex, rowIndex, null\)/);
  assert.match(circuit, /@dragstart="startPaletteDrag\(gate, \$event\)"/);
  assert.match(circuit, /@dragover\.prevent="handleDragOver\(columnIndex, row\)"/);
  assert.match(circuit, /@drop\.prevent="handleDrop\(columnIndex, row\)"/);
  assert.match(circuit, /@dragstart="startCellDrag\(columnIndex, row, \$event\)"/);
  assert.match(circuit, /isDropTarget\(columnIndex, row\)/);
  assert.match(stages, /Circuit Stages/);
  assert.match(stages, /Stage Inspector/);
  assert.match(stages, /PAdicNumericGlyph/);
  assert.match(stages, /digit_vector \(fractal\)/);
  assert.match(stages, /primary map: digit_vector fractal over full rho\[i,j\] entries/);
  assert.match(stages, /Outcome shell and digit detail/);
  assert.match(stages, /position: descriptor digits \(row\/column\) plus p-adic entry digits/);
  assert.match(stages, /node intensity: \|rho\[i,j\]\|_p \(no filtering\)/);
  assert.match(stages, /node color: residue class u \(mod p\), with \|rho\[i,j\]\|_p increasing saturation/);
  assert.match(stages, /node stroke: diagonal entries use light outline, off-diagonal entries use amber outline/);
  assert.equal(stages.includes("changed from previous stage"), false);
  assert.equal(stages.includes("highlight-ids"), false);
  assert.match(stages, /padic-output-table/);
  assert.match(stages, /support/);
  assert.match(stages, /non-zero rho\[i,j\]/);
  assert.match(stages, /off-diagonal nz/);
  assert.match(stages, /Operator entry detail \(full rho\)/);
  assert.match(stages, /entry\.value_text/);
  assert.match(stages, /valuation shell/);
  assert.match(stages, /digit prefix/);
  assert.match(stages, /w_norm \(Derived\)/);
  assert.equal(stages.includes("padic-stage-operator"), false);
  assert.equal(stages.includes("operator cell"), false);
  assert.match(glyph, /padic-numeric-glyph-svg/);
  assert.match(glyph, /padic-stage-shell-ring/);
  assert.match(glyph, /padic-stage-residue-axis/);
  assert.equal(glyph.includes("padic-stage-node-label"), false);
  assert.equal(glyph.includes("highlightIds"), false);
  assert.match(derivedMap, /Derived Geometry/);
  assert.match(derivedMap, /PAdicNumericGlyph/);
  assert.equal(derivedMap.includes("highlight-ids"), false);
  assert.match(sources, /Entropy 25\(1\):86/);
  assert.match(sources, /PubMed PMID 36673227/);
  assert.match(sources, /PMCID PMC9857597/);
  assert.match(sources, /Emergent Mind topic page/);
  assert.equal(stages.includes("Bloch"), false);
  assert.equal(stages.includes("BlochPairView"), false);
  assert.equal(stages.includes("CircuitStageSnapshots"), false);
  assert.equal(stages.includes("StageInspector"), false);
  assert.equal(stages.toLowerCase().includes("probability"), false);
  assert.match(workbench, /PAdicGeneralInputPanel/);
  assert.match(workbench, /PAdicCircuitPanel/);
  assert.match(workbench, /PAdicSourcesPanel/);
  assert.match(workbench, /PAdicCircuitPanel[\s\S]*PAdicStageCards/);
  assert.equal(workbench.includes("PAdicStageCards />\n      <PAdicCircuitPanel"), false);
});
